Hi there! I'm Daphne Smith (she/her) and I am currently getting my M.S. in Geosciences at the University of Texas at Austin. My research focuses on the dynamics of unsaturated fractured bedrock deep root zone water storage, and how they connect to drought in Central Texas.

In my free time I'm an avid cyclist, runner, and hiker. I love being outside in any capacity whether for recreation or doing field work.

<!--
**daphnecs/daphnecs** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working 
- 🌱 I’m currently learning 
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
